# cloudbuild.yaml

serviceAccount: "309015187694-compute@developer.gserviceaccount.com"

# 1) Ensure logs are stored in a user-owned, regional bucket.
options:
  defaultLogsBucketBehavior: "REGIONAL_USER_OWNED_BUCKET"

steps:
  # 2) Build & push your image via the 'pack' flag to gcloud:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud builds submit \
          --pack=gcr.io/buildpacks/builder:latest \
          --tag=us-central1-docker.pkg.dev/from-caves-to-ca-1746047629693/cloud-run-source-deploy:${SHORT_SHA} \
          .

  # 3) Deploy the built image to Cloud Run.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy fromcavestocars \
          --image us-central1-docker.pkg.dev/from-caves-to-ca-1746047629693/cloud-run-source-deploy:${SHORT_SHA} \
          --region us-central1 \
          --platform managed \
          --quiet

# 4) Tell Cloud Build which image(s) to push to Artifact Registry.
images:
  - "us-central1-docker.pkg.dev/from-caves-to-ca-1746047629693/cloud-run-source-deploy:${SHORT_SHA}"
