# Use a regional, user-owned bucket for logs
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET  # :contentReference[oaicite:4]{index=4}

# Reusable substitutions
substitutions:
  _REGION: us-central1
  _PROJECT: from-caves-to-ca-1746047629693
  _SERVICE_ACCOUNT: 309015187694-compute@developer.gserviceaccount.com

# Tell Cloud Build which image to publish
images:
  - "${_REGION}-docker.pkg.dev/from-caves-to-ca-1746047629693/cloud-run-source-deploy/flask-service:${SHORT_SHA}"  # :contentReference[oaicite:5]{index=5}

steps:
  # 1) Build & publish image with Buildpacks via Pack CLI
  - name: "gcr.io/k8s-skaffold/pack"
    entrypoint: "pack"
    args:
      - "build"
      - "${_REGION}-docker.pkg.dev/from-caves-to-ca-1746047629693/cloud-run-source-deploy/flask-service:${SHORT_SHA}"
      - "--builder"
      - "gcr.io/buildpacks/builder:latest"
      - "--network"
      - "cloudbuild"  # ensures network access during build :contentReference[oaicite:6]{index=6}

  # 2) Deploy the image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy flask-service \
          --project=${_PROJECT} \
          --region=${_REGION} \
          --image=${_REGION}-docker.pkg.dev/from-caves-to-ca-1746047629693/cloud-run-source-deploy/flask-service:${SHORT_SHA} \
          --platform=managed \
          --service-account=${_SERVICE_ACCOUNT} \
          --quiet  # suppress prompts in CI :contentReference[oaicite:7]{index=7}
