name: PR Test Status

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        id: tests
        run: |
          # Run the main test script
          python test_openaiquerylib.py || exit 1
          echo "tests_passed=true" >> $GITHUB_OUTPUT
        continue-on-error: true
        
      - name: Mark PR as ready if tests pass
        if: steps.tests.outputs.tests_passed == 'true' && github.event.pull_request.draft == true
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              draft: false
            })
            console.log('PR has been marked as ready for review since tests passed!')